# Site
name: "CosmicVarta"
title: " Welcome to CosmicVarta."
description: " Platform for promoting Indian astronomy research to the public."
logo: 'assets/images/cv.png'
favicon: 'assets/images/cv.png'
baseurl:
google_analytics:
disqus:
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
 Vivek:
    name: Vivek Kumar Jha
    display_name: Vivek Kumar Jha
    avatar: assets/images/vivek.jpg
    email: cosmicvarta@gmail.com
    web: https://viveikjha.github.io
    twitter: https://www.researchgate.net/profile/Vivek-Jha-9
    description: "Ph.D. student in extragalactic astrophysics. Interested in resolving the innermost regions of Supermassive black holes in AGN."

 Lakshitha:
    name: Lakshitha Nama
    display_name: Lakshitha Nama
    avatar: 'assets/images/lakshitha1.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Lakshitha-Mahesh
    twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
    description: "Research scholar working in the field of solar and stellar spectroscopy, trying to understand their atmosphere."

 Ketan:
    name: Ketan
    display_name: Ketan
    avatar: 'assets/images/ketan.jpg'
    email: cosmicvarta@gmail.com
    web: https://twitter.com/rikame_ketan
    twitter: https://twitter.com/rikame_ketan
    description: "PhD student in high energy astrophysics studying accretion powered pulsars. Research interests include astronomy instrumentation and data analysis."

 Anusha:
    name: Anusha
    display_name: Anusha
    avatar: 'assets/images/anusha.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Anusha-Ravikumar-2
    twitter: https://www.researchgate.net/profile/Anusha-Ravikumar-2
    description: "Anusha currently works as a Ph.D. scholar at the University of Western Ontario studying emission-line stars observationally and trying to understand their evolution and properties"

 Gourav:
        name: Gourav
        display_name: Gourav Banerjee
        avatar: 'assets/images/gourav.jpg'
        email: cosmicvarta@gmail.com
        web: https://www.researchgate.net/profile/Gourav-Banerjee-2
        twitter: https://www.researchgate.net/profile/Gourav-Banerjee-2
        description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Anjasha:
      name: Anjasha
      display_name: Anjasha
      avatar: 'assets/images/gourav.jpg'
      email: cosmicvarta@gmail.com
      web: https://www.researchgate.net/profile/Lakshitha-Mahesh
      twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
      description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Vishal Upendran:
      name: Vishal Upendran
      display_name: Vishal Upendran
      avatar: 'assets/images/vishal_upendran.jpg'
      email: uvishal1995@gmail.com
      web: https://vishal-upendran.github.io/
      twitter: https://vishal-upendran.github.io/
      description: "Vishal is a 4th year research scholar at the Inter University Centre for Astronomy and Astrophysics, Pune. He studies various aspects of the solar atmosphere and near-Earth spaceweather. He does so through space and ground based astronomy, theoretical simulations and through machine learning."


 Aritra Chakrabarty:
      name: Aritra Chakrabarty
      display_name: Aritra Chakrabarty
      avatar: 'assets/images/aritra_c.jpg'
      email: aritra@iiap.res.in
      web: https://linkedin.com/in/aritra-chakrabarty-60149077/
      twitter: https://linkedin.com/in/aritra-chakrabarty-60149077/
      description: "I am a postdoctoral researcher at the Indian Institute of Astrophysics working on the characterization of exoplanets. My primary research interest lies in modeling and simulating the physio-chemical processes occurring in the atmospheres of the exoplanets. I also perform indirect observation of the close-in exoplanets using Indian telescopes."

 Vishnu Madhu:
      name: Vishnu Madhu
      display_name: Vishnu Madhu
      avatar: 'assets/images/vishnu_profile.png'
      email: vishnu.mthss@gmail.com
      web: https://www.researchgate.net/profile/Vishnu-Madhu-2
      twitter: https://www.facebook.com/vishnu.madhu.144
      description: "I'm a PhD student at the Indian Institute of Astrophysics, Bengaluru. My topic of research is solar physics, particularly solar magnetic field and spectropolarimetry."

 Bibhuti Kumar Jha:
      name: Bibhuti Kumar Jha
      display_name: Bibhuti Kumar Jha
      avatar: 'assets/images/bibhuti_profile.png'
      email: maitraibibhu@gmail.com
      web: https://bibhuraushan.github.io
      twitter: https://bibhuraushan.github.io
      description: "I am a senior research fellow at IIA, Banglore and ARIES, Nainital working in the area of Solar Astrophysics."

 Robin Thomas:
      name: Robin Thomas
      display_name: Robin Thomas
      avatar: 'assets/images/avatar.png'
      email: robin.thomas@christuniversity.in
      web:
      twitter:
      description: "I am a research scholar at CHRIST (Deemed to be University), carrying out my research in Extragalactic astronomy. "


 Suman Bhattacharyya:
      name: Suman Bhattacharyya
      display_name: Suman Bhattacharyya
      avatar: 'assets/images/suman_profile.jpeg'
      email: suman.acharyya00@gmail.com
      web: https://www.researchgate.net/profile/Suman-Bhattacharyya-2
      twitter: https://www.researchgate.net/profile/Suman-Bhattacharyya-2
      description: "I am Suman, Ph.D. scholar at CHRIST (Deemed to be University). My area of research is the observational and statistical study of emission-line stars to investigate the circumstellar surroundings, disk dynamics, variability. Recently we have identified and described a rare set of candidates in a transition phase from classical Be (CBe) star to Herbig Ae/Be (HAeBe) star (Bhattacharyya et al, 2021). Apart from all this as a pastime, I like to do sketching, reading, and cycling."

 Karthik Rajeev:
      name: Karthik Rajeev
      display_name: Karthik Rajeev
      avatar: 'assets/images/avatar.png'
      email: karthikrajeev.kr@gmail.com
      web:
      twitter:
      description: "Dr. Karthik Rajeev is a post doctoral researcher at the Indian Association for Cultivation of Sciences  IACS, Kolkata). After completing Integrated MSc in Physics from IISER Thiruvananthapuram, in 2015, Karthik joined IUCAA for PhD. He worked with Prof. Thanu Padmanabhan for his thesis on 'Aspects of semi-classical limit and the backreaction problem'. He was the last student of Prof. Thanu Padmanabhan."


 Harsh Mathur:
      name: Harsh Mathur
      display_name: Harsh Mathur
      avatar: 'assets/images/harsh_profile.jpg'
      email: harsh.mathur@iiap.res.in
      web:
      twitter:
      description: "I am a Senior Research Fellow working in IIA Bangalore in the field of Solar Physics"

 Surajit Kalita:
      name: Surajit Kalita
      display_name: Surajit Kalita
      avatar: 'assets/images/surajit_kalita.png'
      email: harsh.mathur@iiap.res.in
      web: https://scholar.google.com/citations?user=ysrlxXMAAAAJ&hl=en&oi=ao
      twitter: https://scholar.google.com/citations?user=ysrlxXMAAAAJ&hl=en&oi=ao
      description: "I have recently completed Ph.D. from the Indian Institute of Science, Bangalore, and will be joining the University of Cape Town for postdoctoral research. My research interest focuses on different aspects of general relativity, gravitational waves, noncommutative geometry, and their applications in compact objects"

 Shridharan Baskaran:
      name: Shridharan Baskaran
      display_name: Shridharan Baskaran
      avatar: 'assets/images/avatar.png'
      email: shridharan.1997@gmail.com
      web:
      twitter:
      description: "I'm a Research Scholar currently working at CHRIST University, Bangalore. I study hot emission-line stars, in particular young hot stars."

 Ankit Kumar:
       name: Ankit Kumar
       display_name: Ankit Kumar
       avatar: 'assets/images/ankit_profile.JPG'
       email: ankit.kumar@iiap.res.in
       web: https://galaxtronomer.wordpress.com/
       twitter: https://galaxtronomer.wordpress.com/
       description: "I am a Senior Research Fellow at Indian Institute of Astrophysics, bangalore and associated with Indian Institute of Science, Bangalore. My research interest lies in the field of galactic dynamics and structure evolution."

 Sunil Simha :
       name: Sunil Simha
       display_name: Sunil Simha
       avatar: 'assets/images/avatar.png'
       email:
       web:
       twitter:
       description: "Sunil is a graduate student of Astronomy at the University of California, Santa Cruz. His research focuses on using Fast Radio Bursts as probes of ionized matter on cosmological scales."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
