# Site
name: "CosmicVarta"
title: " Welcome to CosmicVarta."
description: " Platform for promoting Indian astronomy research to the public."
logo: 'assets/images/cv.png'
favicon: 'assets/images/cv.png'
baseurl:
google_analytics:
disqus:
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
 Vivek:
    name: Vivek Kumar Jha
    display_name: Vivek Kumar Jha
    avatar: assets/images/vivek.jpg
    email: cosmicvarta@gmail.com
    web: https://viveikjha.github.io
    twitter: https://www.researchgate.net/profile/Vivek-Jha-9
    description: "Ph.D. student in extragalactic astrophysics. Interested in resolving the innermost regions of Supermassive black holes in AGN."

 Lakshitha:
    name: Lakshitha Nama
    display_name: Lakshitha Nama
    avatar: 'assets/images/lakshitha.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Lakshitha-Mahesh
    twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
    description: "Research scholar working in the field of solar and stellar spectroscopy, trying to understand their atmosphere."

 Ketan:
    name: Ketan
    display_name: Ketan
    avatar: 'assets/images/ketan.jpg'
    email: cosmicvarta@gmail.com
    web: https://twitter.com/rikame_ketan
    twitter: https://twitter.com/rikame_ketan
    description: "PhD student in high energy astrophysics studying accretion powered pulsars. Research interests include astronomy instrumentation and data analysis."

 Anusha:
    name: Anusha
    display_name: Anusha
    avatar: 'assets/images/anusha.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Anusha-Ravikumar-2
    twitter: https://www.researchgate.net/profile/Anusha-Ravikumar-2
    description: "Anusha currently works as a Ph.D. scholar at the University of Western Ontario studying emission-line stars observationally and trying to understand their evolution and properties"

 Gourav:
        name: Gourav
        display_name: Gourav Banerjee
        avatar: 'assets/images/gourav.jpg'
        email: cosmicvarta@gmail.com
        web: https://www.researchgate.net/profile/Gourav-Banerjee-2
        twitter: https://www.researchgate.net/profile/Gourav-Banerjee-2
        description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Anjasha:
      name: Anjasha
      display_name: Anjasha
      avatar: 'assets/images/gourav.jpg'
      email: cosmicvarta@gmail.com
      web: https://www.researchgate.net/profile/Lakshitha-Mahesh
      twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
      description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Vishal Upendran:
      name: Vishal Upendran
      display_name: Vishal Upendran
      avatar: 'assets/images/vishal_upendran.jpg'
      email: uvishal1995@gmail.com
      web: https://vishal-upendran.github.io/
      twitter: https://vishal-upendran.github.io/
      description: "Vishal is a 4th year research scholar at the Inter University Centre for Astronomy and Astrophysics, Pune. He studies various aspects of the solar atmosphere and near-Earth spaceweather. He does so through space and ground based astronomy, theoretical simulations and through machine learning."


 Aritra Chakrabarty:
      name: Aritra Chakrabarty
      display_name: Aritra Chakrabarty
      avatar: 'assets/images/aritra_c.jpg'
      email: aritra@iiap.res.in
      web: https://linkedin.com/in/aritra-chakrabarty-60149077/
      twitter: https://linkedin.com/in/aritra-chakrabarty-60149077/
      description: "I am a postdoctoral researcher at the Indian Institute of Astrophysics working on the characterization of exoplanets. My primary research interest lies in modeling and simulating the physio-chemical processes occurring in the atmospheres of the exoplanets. I also perform indirect observation of the close-in exoplanets using Indian telescopes."

 Vishnu Madhu:
      name: Vishnu Madhu
      display_name: Vishnu Madhu
      avatar: 'assets/images/vishnu_profile.png'
      email: vishnu.mthss@gmail.com
      web: https://www.researchgate.net/profile/Vishnu-Madhu-2
      twitter: https://www.facebook.com/vishnu.madhu.144
      description: "I'm a PhD student at the Indian Institute of Astrophysics, Bengaluru. My topic of research is solar physics, particularly solar magnetic field and spectropolarimetry."

 Bibhuti Kumar Jha:
      name: Bibhuti Kumar Jha
      display_name: Bibhuti Kumar Jha
      avatar: 'assets/images/bibhuti_profile.png'
      email: maitraibibhu@gmail.com
      web: https://bibhuraushan.github.io
      twitter: https://bibhuraushan.github.io
      description: "I am a senior research fellow at IIA, Banglore and ARIES, Nainital working in the area of Solar Astrophysics."

 Robin Thomas:
      name: Robin Thomas
      display_name: Robin Thomas
      avatar: 'assets/images/avatar.png'
      email: robin.thomas@christuniversity.in
      web:
      twitter:
      description: "I am a research scholar at CHRIST (Deemed to be University), carrying out my research in Extragalactic astronomy. "


 Suman Bhattacharyya:
      name: Suman Bhattacharyya
      display_name: Suman Bhattacharyya
      avatar: 'assets/images/suman_profile.jpeg'
      email: suman.acharyya00@gmail.com
      web: https://www.researchgate.net/profile/Suman-Bhattacharyya-2
      twitter: https://www.researchgate.net/profile/Suman-Bhattacharyya-2
      description: "I am Suman, Ph.D. scholar at CHRIST (Deemed to be University). My area of research is the observational and statistical study of emission-line stars to investigate the circumstellar surroundings, disk dynamics, variability. Recently we have identified and described a rare set of candidates in a transition phase from classical Be (CBe) star to Herbig Ae/Be (HAeBe) star (Bhattacharyya et al, 2021). Apart from all this as a pastime, I like to do sketching, reading, and cycling."

 Karthik Rajeev:
      name: Karthik Rajeev
      display_name: Karthik Rajeev
      avatar: 'assets/images/avatar.png'
      email: karthikrajeev.kr@gmail.com
      web:
      twitter:
      description: "Dr. Karthik Rajeev is a post doctoral researcher at the Indian Association for Cultivation of Sciences  IACS, Kolkata). After completing Integrated MSc in Physics from IISER Thiruvananthapuram, in 2015, Karthik joined IUCAA for PhD. He worked with Prof. Thanu Padmanabhan for his thesis on 'Aspects of semi-classical limit and the backreaction problem'. He was the last student of Prof. Thanu Padmanabhan."


 Harsh Mathur:
      name: Harsh Mathur
      display_name: Harsh Mathur
      avatar: 'assets/images/harsh_profile.jpg'
      email: harsh.mathur@iiap.res.in
      web:
      twitter:
      description: "I am a Senior Research Fellow working in IIA Bangalore in the field of Solar Physics"

 Surajit Kalita:
      name: Surajit Kalita
      display_name: Surajit Kalita
      avatar: 'assets/images/surajit_kalita.png'
      email: harsh.mathur@iiap.res.in
      web: https://scholar.google.com/citations?user=ysrlxXMAAAAJ&hl=en&oi=ao
      twitter: https://scholar.google.com/citations?user=ysrlxXMAAAAJ&hl=en&oi=ao
      description: "I have recently completed Ph.D. from the Indian Institute of Science, Bangalore, and will be joining the University of Cape Town for postdoctoral research. My research interest focuses on different aspects of general relativity, gravitational waves, noncommutative geometry, and their applications in compact objects"

 Shridharan Baskaran:
      name: Shridharan Baskaran
      display_name: Shridharan Baskaran
      avatar: 'assets/images/avatar.png'
      email: shridharan.1997@gmail.com
      web:
      twitter:
      description: "I'm a Research Scholar currently working at CHRIST University, Bangalore. I study hot emission-line stars, in particular young hot stars."

 Ankit Kumar:
       name: Ankit Kumar
       display_name: Ankit Kumar
       avatar: 'assets/images/ankit_profile.JPG'
       email: ankit.kumar@iiap.res.in
       web: https://galaxtronomer.wordpress.com/
       twitter: https://galaxtronomer.wordpress.com/
       description: "I am a Senior Research Fellow at Indian Institute of Astrophysics, bangalore and associated with Indian Institute of Science, Bangalore. My research interest lies in the field of galactic dynamics and structure evolution."

 Sunil Simha :
       name: Sunil Simha
       display_name: Sunil Simha
       avatar: 'assets/images/sunil_profile.jpg'
       email: shassans@ucsc.edu
       web: https://www.linkedin.com/in/sunil-simha-hs/
       twitter: https://www.linkedin.com/in/sunil-simha-hs/
       description: "Sunil Simha is an astronomy graduate student at the University of California Santa Cruz. His work is primarily observational and involves the use of Fast Radio Bursts as Comological probes. When not researching cosmology, he's involved in detector testing for Keck instruments and playing copious amounts of chess."

 Shreya Fadanavis:
       name: Shreya Fadanavis
       display_name: Shreya Fadanavis
       avatar: 'assets/images/shreya_fadanavis.jpg'
       email: shreyafadanavis@gmail.com
       web: http://www.linkedin.com/in/shreya-fadanavis
       twitter: http://www.linkedin.com/in/shreya-fadanavis
       description: "I am a Junior Research Fellow at the Amity Centre of Excellence in Astrobiology (ACoeA), Mumbai. I am currently involved in studying the effect of microgravity on the growth of plants and bacteria."

 Amit Kumar Mandal:
       name: Amit Kumar Mandal
       display_name: Amit Kumar Mandal
       avatar: 'assets/images/amit_profile.jpg'
       email: amitastro.am@gmail.com
       web: https://www.researchgate.net/profile/Amit-Mandal-10
       twitter: https://www.researchgate.net/profile/Amit-Mandal-10
       description: "I am a Post Doctoral Researcher (PDR) at Seoul National University (SNU), South Korea with Prof. Jong-Hak Woo. Currently I am involved in SNU AGN Monitoring Project (SAMP) aiming to find the black hole masses and study of the structure and kinematics of the innermost regions in AGN."

 CosmicVarta:
        name: CosmicVarta
        display_name: CosmicVarta
        avatar: 'assets/images/thumb.png'
        email: cosmicvarta@gmail.com
        web: http://www.cosmicvarta.in
        twitter: http://www.twitter.com/cosmicvarta
        description: "Written by the CosmicVarta team. This article has been authored by all the members as a joint effort."

 Akhil Jaini:
        name: Akhil Jaini
        display_name: Akhil Jaini
        avatar: 'assets/images/akhil_jaini.png'
        email: work.jainiakhil@gmail.com
        web: https://www.linkedin.com/in/jainiakhil
        twitter: https://www.facebook.com/jainiakhilsuper
        description: "I am currently pursuing my Masters in Astronomical Instrumentation from the Indian Institute of Astrophysics, Bengaluru. My research interests are in Radio Astronomy, Exoplanet Science and Astronomical Instrumentation."
 
 Gourab Giri:
        name: Gourab Giri
        display_name: Gourab Giri
        avatar: 'assets/images/gourab_giri.png'
        email: gourabgiri99@gmail.com
        web: https://sites.google.com/iiti.ac.in/gourabgiri/home
        twitter: https://sites.google.com/iiti.ac.in/gourabgiri/home
        description: "My name is Gourab Giri, a PhD scholar at the Indian Institute of Technology Indore, India. I am also a Prime Minister Research Fellow selected in May 2020 cycle. My research is mostly focused on understanding galaxy evolution; however, I generally remain excited about any topic in astrophysics."
 
 Saurabh Singh:
        name: Saurabh Singh
        display_name: Saurabh Singh
        avatar: 'assets/images/saurabh_singh.jpg'
        email: saurabhs@rri.res.in
        web: https://www.rri.res.in/people/faculty/saurabh-singh
        twitter: https://www.rri.res.in/people/faculty/saurabh-singh
        description: "Saurabh Singh is an Assistant Professor at Raman Research Institute (RRI), Bangalore. Saurabh's research focuses on experimental cosmology. He designs experiments to understand crucial epochs of the Universe, such as cosmic dawn, the epoch of reionization, and the era of dark energy domination, via 21-cm intensity mapping."

 Yash Bhargava:
        name: Yash Bhargava
        display_name: Yash Bhargava
        avatar: 'assets/images/yash_bhargava.jfif'
        email: yash@iucaa.in
        web: https://www.linkedin.com/in/yashbhargava1992/
        twitter: https://www.linkedin.com/in/yashbhargava1992/
        description: "Yash works on the X-ray observations of Black hole binaries. His focus is on spectro-timing studies to unravel the physics around these enigmatic objects."        



 Ekta Sharma:
        name: Ekta Sharma
        display_name: Ekta Sharma
        avatar: 'assets/images/ekta_sharma.jpg'
        email: ektasharma.astro@gmail.com
        web: 
        twitter: 
        description: "I am a postdoctoral fellow at National Astronomical Observatories of China (NAOC), China in the ISM group. Currently, I am involved in studying observational aspects of ealy stages of star formation using single-dish radio facility FAST. "

 Ashish Devraj:
        name: Ashish Devraj
        display_name: Ashish Devraj
        avatar: 'assets/images/ashish_devraj.jpg'
        email: 
        web: https://www.researchgate.net/profile/Ashish-Devaraj
        twitter: https://www.researchgate.net/profile/Ashish-Devaraj
        description: "Ashish Devraj is a PhD student at CHRIST (Deemed to be University), who works on lunar physics. "

 Biswajit Mondal:
        name: Biswajit Mondal
        display_name: Biswajit Mondal
        avatar: 'assets/images/biswajit_mondal.jpg'
        email:
        web: https://www.researchgate.net/profile/Biswajit-Mondal-8
        twitter: https://www.researchgate.net/profile/Biswajit-Mondal-8
        description: "I am a research scholar at Physical Research Laboratory, Ahmedabad, India. Currently, I am involved in studying coronal X-ray characteristics of the Sun. I am also involved in the development of X-ray instrumentation for astronomical observations."


 
 Sagnik Chatterjee:
        name: Sagnik Chatterjee
        display_name: Sagnik Chatterjee
        avatar: 'assets/images/Sagnik_pic.jpg'
        email:
        web: https://sites.google.com/view/sagnikchatterjee/home?authuser=1
        twitter: https://sites.google.com/view/sagnikchatterjee/home?authuser=1
        description: " I am a Prime Minister's Research Fellow (PMRF) at IISER Bhopal. I work on compact objects like neutron stars. My work mainly involves the theoretical and computational aspects of such stars. "

 Rahul Gupta:
        name: Rahul Gupta
        display_name: Rahul Gupta
        avatar: 'assets/images/rahul_gupta.jpeg'
        email: rahulbhu.c157@gmail.com
        web: https://www.researchgate.net/profile/Rahul-Gupta-140
        twitter: https://www.researchgate.net/profile/Rahul-Gupta-140
        description: " I am Rahul Gupta, currently working as a Ph.D. student at the Department of Astronomy and Astrophysics, Aryabhatta Research Institute of Observational Sciences (ARIES), India. My research work is mainly focused on time-domain astronomy (towards Gamma-ray bursts (GRBs) and their afterglows, Supernovae (SNe), and other transients) based on data from across the electromagnetic band. Presently, I am interested in prompt emission (Gamma and X-rays) spectro-polarimetric studies of GRBs using AstroSat CZTI observations."


 Amar Aryan:
        name: Amar Aryan
        display_name: Amar Aryan
        avatar: 'assets/images/amar_aryan.jpg'
        email: amar@aries.res.in
        web: https://www.researchgate.net/profile/Amar-Aryan
        twitter: https://www.researchgate.net/profile/Amar-Aryan
        description: "I am a Senior Research Fellow (SRF) at Aryabhatta Research Institute of observational sciencES (ARIES), Nainital, Uttarakhand, India. My research interests mainly include transients such as core-collapse supernovae of various types and Gamma-ray bursts. I use various openly available tools such as MESA, STELLA, SNEC, MOSFiT, SNcosmo, etc., for multiple analyses."


 Neelam Panwar:
        name: Neelam Panwar
        display_name: Neelam Panwar
        avatar: 'assets/images/neelam.jpg'
        email: neelam@aries.res.in
        web: https://www.researchgate.net/profile/Neelam-Panwar
        twitter: https://www.researchgate.net/profile/Neelam-Panwar
        description: "I am Neelam Panwar, working as a Scientist at Aryabhatta Research Institute of Observational Sciences (ARIES), India. My research interest are  to study star formation in young clusters, bright-rimmed cloud and HII regions, and variability in T-Tauri stars."



 Sneha Kachhara:
        name: Sneha Kachhara
        display_name: Sneha Kachhara
        avatar: 'assets/images/female_avatar.png'
        email: snehakachhara@students.iisertirupati.ac.in
        web: https://nonlinearsystems.wordpress.com/
        twitter: https://nonlinearsystems.wordpress.com/
        description: "I study complex networks, dynamical systems and their applications in areas spanning from physiology to astrophysics. I am currently a postdoctoral scholar at Northwestern University."


 Himansh Kavin:
        name: Himansh Rathore, Kavin Kumar
        display_name: Himansh Rathore, Kavin Kumar
        avatar: 'assets/images/avatar.png'
        email: 
        web: 
        twitter: 
        description: "Himansh Rathore participated in this work as an undergrad from the Department of Physics, Indian Institute of Technology Bombay. He is currently pursuing a PhD from the Department of Astronomy, University of Arizona. Kavin Kumar is from the Department of Physics, Indian Institute of Science Education and Research Bhopal, and is currently pursuing his masters thesis from the National Center for Radio Astrophysics, Pune."

 Parul Janagal:
        name: Parul Janagal
        display_name: Parul Janagal
        avatar: 'assets/images/parul_janagal.jpeg'
        email: phd1801121004@iiti.ac.in
        web: https://sites.google.com/view/paruljanagal/home?authuser=0
        twitter: https://www.linkedin.com/in/parul-janagal/?originalSubdomain=in
        description: "I'm a final year PhD Scholar currently excavating secrets of the universe as an Astrophysicist. Beyond my obvious love for pulsars, I like to read and do DIY projects. I'm also obsessed with Astrophotography, and one can always find me lurking in the shadows, trying to find a clean spot to see the stars."

 Shashank Pandey:
        name: Shashank Pandey
        display_name: Shashank Pandey
        avatar: 'assets/images/avatar.png'
        email: 
        web: 
        twitter: 
        description: "PhD scholar at the department of Astrophysics and Cosmology, S.N. Bose National Centre for Basic Sciences, Kolkata."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
