# Site
name: "CosmicVarta"
title: " Welcome to CosmicVarta."
description: " Platform for promoting Indian astronomy research to the public."
logo: 'assets/images/cv.png'
favicon: 'assets/images/cv.png'
baseurl:
google_analytics: 'UA-46278016-1'
disqus:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
 Vivek:
    name: Vivek Kumar Jha
    display_name: Vivek Kumar Jha
    avatar: assets/images/vivek.jpg
    email: cosmicvarta@gmail.com
    web: https://viveikjha.github.io
    twitter: https://www.researchgate.net/profile/Vivek-Jha-9
    description: "Ph.D. student in extragalactic astrophysics. Interested in resolving the innermost regions of Supermassive black holes in AGN."

 Lakshitha:
    name: Lakshitha Nama
    display_name: Lakshitha Nama
    avatar: 'assets/images/lakshitha.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Lakshitha-Mahesh
    twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
    description: "Research scholar working in the field of solar and stellar spectroscopy, trying to understand their atmosphere."

 Ketan:
    name: Ketan
    display_name: Ketan
    avatar: 'assets/images/ketan.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Lakshitha-Mahesh
    twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
    description: "PhD student in high energy astrophysics studying accretion powered pulsars. Research interests include astronomy instrumentation and data analysis."

 Anusha:
    name: Anusha
    display_name: Anusha
    avatar: 'assets/images/anusha.jpg'
    email: cosmicvarta@gmail.com
    web: https://www.researchgate.net/profile/Lakshitha-Mahesh
    twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
    description: "Anusha currently works as a Research Assistant studying emission-line stars observationally and trying to understand their evolution and properties"

 Gourav:
        name: Gourav
        display_name: Gourav Banerjee
        avatar: 'assets/images/gourav.jpg'
        email: cosmicvarta@gmail.com
        web: https://www.researchgate.net/profile/Lakshitha-Mahesh
        twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
        description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Anjasha:
      name: Anjasha
      display_name: Anjasha
      avatar: 'assets/images/gourav.jpg'
      email: cosmicvarta@gmail.com
      web: https://www.researchgate.net/profile/Lakshitha-Mahesh
      twitter: https://www.researchgate.net/profile/Lakshitha-Mahesh
      description: " PhD scholar working in the field of optical spectroscopy of emission-line star studies, especially understanding the disc physics of Classical Be stars."

 Vishal Upendran:
      name: Vishal Upendran
      display_name: Vishal Upendran
      avatar: 'assets/images/vishal_upendran.jpg'
      email: uvishal1995@gmail.com
      web: https://vishal-upendran.github.io/
      twitter: https://vishal-upendran.github.io/
      description: "Vishal is a 4th year research scholar at the Inter University Centre for Astronomy and Astrophysics, Pune. He studies various aspects of the solar atmosphere and near-Earth spaceweather. He does so through space and ground based astronomy, theoretical simulations and through machine learning."


 Aritra Chakrabarty:
      name: Aritra Chakrabarty
      display_name: Aritra Chakrabarty
      avatar: 'assets/images/aritra_c.jpg'
      email: aritra@iiap.res.in
      web: https://linkedin.com/in/aritra-chakrabarty-60149077/
      twitter: https://linkedin.com/in/aritra-chakrabarty-60149077/
      description: "I am a postdoctoral researcher at the Indian Institute of Astrophysics working on the characterization of exoplanets. My primary research interest lies in modeling and simulating the physio-chemical processes occurring in the atmospheres of the exoplanets. I also perform indirect observation of the close-in exoplanets using Indian telescopes."

 Vishnu Madhu:
      name: Vishnu Madhu
      display_name: Vishnu Madhu
      avatar: 'assets/images/vishnu_profile.png'
      email: vishnu.mthss@gmail.com
      web: https://www.researchgate.net/profile/Vishnu-Madhu-2
      twitter: https://www.facebook.com/vishnu.madhu.144
      description: "I'm a PhD student at the Indian Institute of Astrophysics, Bengaluru. My topic of research is solar physics, particularly solar magnetic field and spectropolarimetry."



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
